stages:
  - build
  - deploy

build_img: 
  stage: build
  script:
    # Pull base image
    - docker pull openjdk:8-jdk-slim
    # Build Docker image
    - docker build -t dkr.tw/sgis/geospatialdescription:api ./image
    # Push Docker image to registry
    - docker push dkr.tw/sgis/geospatialdescription:api
    # Remove dangling images
    - docker rmi $(docker images -f "dangling=true" -q) || echo "No dangling images to remove"
  tags:
    - sgis-zone101

deploy_1:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  tags:
    - sgis-zone101
