version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/src
    ports:
      - "8000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
    command: flask run