# 使用官方的 openjdk 與 python 映像檔
FROM openjdk:8-jdk-slim AS builder

# 安裝 Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# 設定工作目錄
WORKDIR /src

# 複製 requirements.txt 並安裝 Python 套件
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

# 複製應用程式碼到工作目錄
COPY ./src /src/

# 設定環境變數
ENV PYTHONUNBUFFERED=1

# 暴露端口
EXPOSE 80

# 執行 Flask 應用程式
CMD ["python3", "main.py"]

